### ISSUE TITLE
Make spacy models an optional install

### ISSUE THREAD

**Issue by zwelz3** [JoelStansbury/ipypdf#1]
Maybe an anaconda project command to install the larger models. Maybe the small model is the default? 
The large model is over 600MB which may be too much for some to want as a dependency.

**Comment by JoelStansbury** [comment]
Hey Zach,
I actually removed Anaconda-project because on my machine because it does not handle the tesseract environment variables correctly. I've been meaning to add it back in for a while though, so I will implement this option when I do so.

As a side note, if en_core_web_lg is not installed at runtime, the spacy tab just shows a button that prompts the user to install it by executing `sys.executable -m spacy.download en_core_web_lg`. I should probably also provide an option to get the `md` model there, but let me know if you think this is unnecessary. 
- Joel

**Comment by zwelz3** [comment]
> Hey Zach, I actually removed Anaconda-project because on my machine because it does not handle the tesseract environment variables correctly. I've been meaning to add it back in for a while though, so I will implement this option when I do so.
> 
> As a side note, if en_core_web_lg is not installed at runtime, the spacy tab just shows a button that prompts the user to install it by executing `sys.executable -m spacy.download en_core_web_lg`. I should probably also provide an option to get the `md` model there, but let me know if you think this is unnecessary.
> 
> * Joel

Yeah but sometimes you want to load a local model or one from modelhub. Not sure what the correct flow for this would be.

**Comment by JoelStansbury** [comment]
That makes sense. I don't anticipate adding any support for modelhub (best not to google this from a work computer). But I'll put some thought into allowing a custom model path.
